// <auto-generated />
namespace WindowsFormsApp32.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class datetime_changed_last : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime_changed_last));
        
        string IMigrationMetadata.Id
        {
            get { return "202202271137179_datetime_changed_last"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
